# Generated by Django 3.1.1 on 2020-09-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200928_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='likes_posts',
            field=models.ManyToManyField(related_name='likes', to='network.Post'),
        ),
    ]
