# Generated by Django 3.1.1 on 2020-09-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200929_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes_posts',
            new_name='likes',
        ),
    ]
