# Generated by Django 3.1 on 2020-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200929_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='network.Post'),
        ),
    ]
