# Generated by Django 3.1 on 2020-08-07 14:16

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200807_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=auctions.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
